### ISSUE TITLE
Checklist for 2.7 Upgrade Notes

### ISSUE THREAD

**Issue by ihcsim** [linkerd/website#607]
Use this issue to track items to be included in the 2.7 upgrade notes. This should be added to the existing [upgrade docs](https://linkerd.io/2/tasks/upgrade/).

* [x] Inform users of the new cert rotation process. To help them to determine if this is relevant to them, show them how to determine the expiry date of their existing certificates, by checking the `linkerd-config` config map and `linkerd-identity-secret` secret. (I don't think `linkerd check` expose that information, unless the validity period expiry is near.) (PR [here](https://github.com/linkerd/website/pull/630))
* [ ] Inform users that the CNI nmespace has changed and advise how to upgrade (https://github.com/linkerd/linkerd2/pull/3903#issuecomment-575406441)

Helm breaking changes: 
These need to be addressed as a more general not. Informing users that things have changed around the helm chart and providing a link to a diff file that they can use in order to bring thir values.yaml up to scratch.

* [x] Notify Helm users that the Helm variables have been converted to lower case, to comply with [Helm best practices](https://helm.sh/docs/topics/chart_best_practices/values/). This is a breaking change for them.
* [x] Notify Helm users that we fixed a typo in the `issuanceLifetime` variable. See https://github.com/linkerd/linkerd2/pull/3887
* [x] Inform Helm users that noInitContainer has changed and advise how to upgrade

* [ ] etc...

**Comment by zaharidichev** [comment]
Added https://github.com/linkerd/website/pull/630 as the first step. Will add the other two once this is merged.
